[package]
name = "cypi"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8" }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.15", features = ["net", "rt", "sync"] }
toml = "0.8.22"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
